AElfProject/aelf-block-explorer

src/pages/Vote/Vote.js
src/pages/Vote/VoteModal/index.js

feat: switchVote

---

src/pages/Vote/VoteModal/index.js

feat: delete lockTime

---

.eslintrc
src/components/Header/HeaderTop.js
src/pages/Home/Home.jsx
src/pages/Home/components/ChainInfo.jsx
src/redux/actions/common.js
src/redux/reducers/common.js
src/utils/deviceCheck.js
src/utils/fetchPriceAndPrevious.js

feat: fix home and headertop interface fetch twice

feat: fix home and headertop interface fetch twice

---

src/pages/Proposal/containers/ProposalDetail/index.less

add nowrap in proposalDetail page

feat: whtie space

---

src/common/utils.js
src/pages/Proposal/containers/ProposalDetail/index.jsx
src/pages/Proposal/containers/ProposalList/Proposal/index.jsx

feat: fix proposal vote bpCount

---

src/_components/AddressDetail/components/Events/columnConfig.tsx
src/_components/AddressDetail/index.tsx
src/_components/ContractToken/index.tsx
src/_components/DetailContainer/index.tsx
src/_components/EPToolTip/index.css
src/_components/EPToolTip/index.tsx
src/_components/Method/index.tsx
src/_components/NFTTransfers/index.tsx
src/_components/Table/index.css
src/_components/TokenTransfers/columnConfig.tsx
src/_components/TokenTransfers/index.tsx
src/app/accounts/columnConfig.tsx
src/app/blocks/columnConfig.tsx
src/app/transactions/columnConfig.tsx
src/pageComponents/home/_components/Latest/index.tsx

feat: add Tooltip components and remove sytle css

feat: add Tooltip components

---

src/_components/AddressDetail/components/Tokens/List/columnConfig.tsx
src/_components/AddressDetail/components/Tokens/List/index.tsx
src/_components/AddressDetail/components/Tokens/List/mock.ts
src/_components/ConfirmedStatus/index.tsx
src/_components/EPSortIcon/index.css
src/_components/EPSortIcon/index.tsx
src/_components/EPToolTip/index.tsx
src/_components/HeaderMenu/index.tsx
src/_components/Table/index.css
src/_components/Table/index.tsx
src/_components/Table/pagination.tsx
src/_components/TransactionsView/index.css
src/_components/TransactionsView/index.tsx
src/_hooks/useTable.ts
src/_style/search.css
src/app/transactions/columnConfig.tsx
src/app/transactions/mock.ts

feat: recover header menu

---

src/_components/AddressDetail/components/Events/index.css
src/_components/AddressDetail/components/Tokens/List/columnConfig.tsx
src/_components/ChainSelect/index.css
src/_components/EPSearch/index.css
src/_components/EPSortIcon/index.tsx
src/_components/EPTabs/index.css
src/_components/EPToolTip/index.css
src/_components/HeaderMenu/index.css
src/_components/HeaderTop/index.css
src/_components/MobileHeaderMenu/index.css
src/_components/Table/index.css
src/_components/Table/index.tsx
src/_components/Table/pagination.css
src/_components/TransactionsView/index.css
src/_style/globals.css
src/_style/nft-details.css
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverViewDetail.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverViewProperty.tsx
src/app/[chain]/tokens/page.tsx
src/app/pageProvider.tsx
src/pageComponents/governance/index.css

add aelf-design provider and prefixCls

feat: add aelf-design provider and prefixCls

---

src/_components/AddressDetail/components/Contract/protocol.tsx
src/_components/AddressDetail/components/Contract/sourceCode.tsx
src/_components/AddressDetail/components/Tokens/List/index.tsx
src/_components/Download/index.tsx
src/_components/EPSearch/index.tsx
src/_components/EPTabs/index.tsx
src/_components/EPToolTip/index.tsx
src/_components/LogsContainer/logItems.tsx
src/_components/Search/SearchBox.tsx
src/_components/Table/pagination.tsx
src/_hooks/useTable.ts
src/_utils/searchRule.ts
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/NFTDetails.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_holders/HoldersTable.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_holders/column.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/ItemActivityTable.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/column.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverView.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/mock.ts
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/page.tsx
src/app/address/[hash]/page.tsx
src/app/block/[hash]/_components/detail.tsx
src/pageComponents/home/_components/Latest/index.tsx

replace antd components with aelfd components

feat: replace antd components with aelfd components

---

src/_components/AddressDetail/components/Events/index.css
src/_components/AddressDetail/components/Events/index.tsx
src/_components/AddressDetail/components/Tokens/List/index.css
src/_components/AddressDetail/components/Tokens/List/index.tsx
src/_components/AddressDetail/components/Tokens/NFTAssets/index.css
src/_components/AddressDetail/components/Tokens/NFTAssets/index.tsx
src/_components/EPSearch/index.tsx
src/_components/NFTTransfers/index.tsx
src/_components/Table/index.tsx
src/_components/TokenTransfers/index.tsx
src/_lib/AntdThemeConfig.ts
src/_utils/typeUtils.ts
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_holders/HoldersTable.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/ItemActivityTable.tsx
src/app/accounts/list.tsx
src/app/block/[hash]/_components/detail.tsx
src/app/blocks/blockList.tsx
src/app/contracts/contractsList.tsx
src/app/pageProvider.tsx
src/app/transactions/list.tsx

change HeadTitle and add table search

feat: change HeadTitle and add table search

---

Dockerfile
compose.yml
next.config.js

feat: add dockerfile

---

src/_api/server.ts
src/_api/type.ts
src/_style/globals.css
src/_types/common.ts
src/_utils/formatter.ts
src/_utils/urlUtils.ts
src/app/[chain]/block/[hash]/_components/baseinfo.tsx
src/app/[chain]/block/[hash]/_components/detail.tsx
src/app/[chain]/block/[hash]/page.tsx
src/app/[chain]/blocks/blockList.tsx
src/app/[chain]/blocks/page.tsx
src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx
src/app/[chain]/token/[tokenSymbol]/page.tsx
src/app/[chain]/token/[tokenSymbol]/type.ts
src/app/[chain]/tokens/page.tsx
src/app/[chain]/tokens/tokensList.tsx

feat: delete blocks request store

---

src/_api/type.ts
src/_utils/formatter.ts
src/app/[chain]/block/[hash]/_components/detail.tsx
src/app/[chain]/blocks/blockList.tsx
src/app/[chain]/blocks/columnConfig.tsx
src/app/[chain]/blocks/page.tsx
src/app/[chain]/tokens/page.tsx
src/app/[chain]/tokens/tokensList.tsx
src/app/transactions/columnConfig.tsx
src/app/transactions/list.tsx

fix: fix blocks jump url

---

src/_components/HeaderTop/index.tsx
src/app/api/revalidate/route.ts

feat: chang icon

---

src/app/[chain]/block/[hash]/layout.tsx
src/app/[chain]/block/[hash]/loading.tsx
src/app/[chain]/blocks/blockList.tsx
src/app/[chain]/blocks/layout.tsx
src/app/[chain]/blocks/loading.tsx
src/app/[chain]/blocks/page.tsx
src/app/[chain]/token/[tokenSymbol]/layout.tsx
src/app/[chain]/token/[tokenSymbol]/loading.tsx
src/app/[chain]/tokens/layout.tsx
src/app/[chain]/tokens/loading.tsx
src/app/[chain]/tx/[hash]/layout.tsx
src/app/[chain]/tx/[hash]/loading.tsx
src/app/actions.ts
src/app/layout.tsx

feat: data cache

---

src/_types/common.ts
src/app/[chain]/nft/[collectionSymbol]/_Detail/_inventory/CardList.tsx
src/app/[chain]/nfts/mock.ts
src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx
src/app/[chain]/token/[tokenSymbol]/type.ts

feat: type error

---

src/_hooks/useHomeSocket.ts
src/_socket/index.ts
src/_socket/signalr.ts
src/pageComponents/home/page.tsx

feat: home data add signalr

---

next.config.js
src/_components/Footer/index.tsx
src/_components/MobileHeaderMenu/index.tsx
src/_utils/env.ts
src/_utils/isMainNet.ts
src/app/[chain]/block/[hash]/_components/baseinfo.tsx
src/app/[chain]/block/[hash]/_components/detail.tsx
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverViewDetail.tsx
src/app/[chain]/token/[tokenSymbol]/_components/Transfers/columns.tsx
src/pageComponents/home/_components/Latest/index.css

hom style and change  isMainNet  use

feat: hom style and change env

---

src/_components/Footer/index.tsx
src/_components/HeaderTop/index.tsx
src/_components/MobileHeaderMenu/index.tsx
src/_utils/isMainNet.ts
src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverViewDetail.tsx

change NEXT_PUBLIC_NETWORK_TYPE env use

feat: change NEXT_PUBLIC_NETWORK_TYPE env use

---

src/_api/fetchNFTS.ts
src/_api/list.ts
src/_api/type.ts
src/_components/Copy/index.tsx
src/_components/Table/index.css
src/app/[chain]/blocks/columnConfig.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/CollectionDetails.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/_overview/OverView.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/detail.css
src/app/[chain]/nft/[collectionSymbol]/_Detail/index.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/type.ts
src/app/[chain]/nft/[collectionSymbol]/layout.tsx
src/app/[chain]/nft/[collectionSymbol]/loading.tsx
src/app/[chain]/transactions/columnConfig.tsx

feat: change table font size

---

src/app/[chain]/nft/[collectionSymbol]/_Detail/index.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/mock.ts

feat: build error

---

src/_api/fetchNFTS.ts
src/_api/type.ts
src/_components/Copy/index.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/CollectionDetails.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/_transfers/Table.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/_transfers/column.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/index.tsx
src/app/[chain]/nft/[collectionSymbol]/_Detail/mock.ts
src/app/[chain]/nft/[collectionSymbol]/_Detail/type.ts
src/app/[chain]/transactions/columnConfig.tsx

collection transfers Interface modulation

feat: collection transfers Interface modulation

---

package.json
src/components/Footer/Footer.js
src/pages/AddressDetail/components/NFTTransfers/index.jsx
src/pages/AddressDetail/components/Tokens/Tokens.jsx
src/pages/AddressDetail/components/Tokens/columnConfig.jsx
src/pages/AddressDetail/components/Transfers/columnConfig.jsx
src/pages/Token/Token.jsx
src/pages/Token/components/Holders.jsx
src/pages/Token/components/Overview.jsx
src/pages/Tokens/Tokens.jsx
src/pages/Tokens/columnConfig.jsx
src/utils/formater.js

1、change symbol to tokenName, e.g. SGR-1 -> SGR
2、add portkey wallet at footer

change symbol to tokenName
